/*
 * Start/stop control for the agent session.
 *
 * WHY A TASK
 *
 * Stopping is slow and blocking: closing the socket writes a CLOSE frame through
 * mbedTLS, and if the press lands mid-handshake it waits out the client's
 * network timeout. The gesture that triggers it arrives on the LVGL task, with
 * the LVGL lock held -- blocking there stalls every render and invites lock
 * inversion. And the WebSocket client refuses stop/close outright when called
 * from its own event task. So the request is signalled, and a worker task
 * pinned away from the audio core does the work.
 *
 * The input side is deliberately not part of this interface. Anything that can
 * call toggle()/restart() works -- today it is a screen gesture, a GPIO button
 * would be a couple of lines.
 */
#pragma once

#include <stdbool.h>

#include "esp_err.h"

#include "dg_agent.h"

/* Creates the worker task. Call after audio_io_init() and ui_start().
 * Does not open a session -- call session_ctl_request_start() for that. */
esp_err_t session_ctl_start(const dg_agent_callbacks_t *callbacks);

/* All non-blocking: they queue a request and return immediately. Safe from any
 * task, including LVGL and WebSocket callbacks. */
void session_ctl_request_start(void);
void session_ctl_request_toggle(void);

/*
 * Stop if running; never start. Idempotent.
 *
 * Distinct from toggle because the idle timeout needs a request that cannot
 * accidentally open a session -- the whole point of it is that an unattended
 * device stops streaming.
 */
void session_ctl_request_stop(void);
void session_ctl_request_restart(void);

/*
 * Ask the worker to write the conversation to flash when it next wakes.
 *
 * Safe from any task, and specifically safe from the WebSocket event task and
 * the esp_timer task, which is the entire reason it exists -- the flash erase
 * behind it blocks for tens of milliseconds with the cache off on both cores,
 * and neither of those tasks can afford that. Unlike every request below it
 * travels as a flag rather than a notification value, so it can never displace
 * a pending gesture; see the comment on s_flush_wanted in the .c.
 */
void session_ctl_request_history_flush(void);

/*
 * Reopen the session, but only if one is up, and never at the cost of a gesture.
 *
 * Distinct from session_ctl_request_reload() above, which posts a notification
 * VALUE and skips the cooldown -- correct for a reload the agent asked for as
 * part of a sentence it is speaking, and wrong for one that fires on a timer.
 * A timer landing on the tap the user just made would replace their toggle with
 * a reload and reopen the session they were ending. This rides alongside the
 * value instead, so it can never displace anything, and it does nothing at all
 * if the session is already down.
 */
void session_ctl_request_reload_soon(void);

/*
 * Repaint the centre label for a device that is stopped, and do nothing if it
 * is not.
 *
 * Exists so that the rule for what a stopped device says lives in exactly one
 * place. Anything that puts a transient message over it -- the forget offer in
 * main.c -- calls this to put it back, rather than carrying its own copy that
 * cannot know whether the last start failed.
 */
void session_ctl_repaint_idle_status(void);

/*
 * Reopen the session to pick up a setting change.
 *
 * Unlike the gesture requests this skips the debounce: it is generated by the
 * agent acting on the user's words, not by a finger that might have brushed the
 * screen, so silently dropping it would strand the device on the old setting.
 */
void session_ctl_request_reload(void);

/* True while a session is meant to be up. Reflects intent, not connectivity --
 * a session that is retrying its socket still counts as running. */
bool session_ctl_is_running(void);

/*
 * How long the current start/stop has been in flight, 0 if none is.
 *
 * This exists as a DEADLOCK BACKSTOP, not as a progress bar. Every request is
 * refused while an action is busy, so an action that never completes is a device
 * that never accepts another gesture -- which is what a stop blocked inside the
 * WebSocket client produced, repeatedly, until the board was physically reset.
 * A start or stop takes milliseconds on a healthy link and a few seconds on a bad
 * one; anything past ten times that is not slow, it is stuck.
 */
uint32_t session_ctl_busy_for_ms(void);

/*
 * Whether a start or stop is in progress at all.
 *
 * Distinct from session_ctl_busy_for_ms() != 0, which is a DURATION and reads
 * zero for the first millisecond of every action. That is fine for the deadlock
 * backstop it was written for and not fine for a gate: the hold gesture uses
 * this to refuse to confirm a forget during a teardown, and a sub-millisecond
 * hole in that gate is a destroyed conversation.
 */
bool session_ctl_is_busy(void);
