#!/usr/bin/env python3
"""Generates the _binary_*_start/_end symbols EMBED_TXTFILES makes on the device.

Assembly rather than C on purpose: _end is a LABEL past the data, which C has no
way to express -- a pointer variable at that symbol would give agent_prompt.c the
address of the pointer instead of the end of the blob, and every block would
come out the wrong length.

Same naming contract as ESP-IDF: the file name with every non-alphanumeric
character turned into an underscore, content followed by a NUL, _end past it.
"""
import pathlib, re, sys

src = pathlib.Path(sys.argv[1]).resolve()
out = ["/* Generated by prompt_blobs.py -- do not edit. */", ".data"]
for path in sorted(src.glob("*.md")):
    sym = re.sub(r"[^0-9a-zA-Z]", "_", path.name)
    out += [
        f".globl _binary_{sym}_start",
        f"_binary_{sym}_start:",
        f'.incbin "{path}"',
        ".byte 0",
        f".globl _binary_{sym}_end",
        f"_binary_{sym}_end:",
        "",
    ]
print("\n".join(out))
